apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  ingressClassName: public
  rules:
    - http:
        paths:
          - backend:
              service:
                name: helloworld-srv
                port:
                  number: 8080
            path: /
            pathType: Prefix
